site_name: Maker Thursday
site_url: https://tinkerhub.github.io/makerthursday

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - blog
  - search

nav:
  - index.md
  - Journal:
    - blog/index.md

# Extensions
markdown_extensions:
  - admonition