authors:
  salman:
    name: Salman Faris
    description: Team MakerGram
    avatar: https://avatars.githubusercontent.com/u/11945360
    url: https://github.com/salmanfarisvp
  devadath:
    name: Devadath S
    description: Team TinkerSpace
    avatar: https://avatars.githubusercontent.com/u/95075234?v=4
    url: https://tinkerhub.org/@dev_devadath
  ramakanth:
    name: Ramakanth V Prabhu
    description: Team TinkerSpace
    avatar: https://avatars.githubusercontent.com/u/36660845
    url: https://tinkerhub.org/@ramakanth
  abdulsamadmj:
    name: Abdul Samad M J
    description: Team TinkerSpace
    avatar: https://avatars.githubusercontent.com/u/73947768?v=4
    url: https://tinkerhub.org/@abdulsamadmj
  amaljith:
    name: Amal Jith
    description: Team TinkerSpace
    avatar: https://avatars.githubusercontent.com/u/269922746?v=4
    url: https://app.tinkerhub.org/u/TZK53H4B9R