authors:
  salman:
    name: Salman Faris
    description: Team MakerGram
    avatar: https://avatars.githubusercontent.com/u/11945360
    url: https://github.com/salmanfarisvp
  devadath:
    name: Devadath S
    description: Team TinkerSpace
    avatar: https://avatars.githubusercontent.com/u/95075234?v=4
    url: https://tinkerhub.org/@dev_devadath